# -*- coding: utf-8 -*-
"""All the string keys from the configuration files.

Created on Tue Jul 25 07:43:16 2023
@author: Ann"""


ABOUT = 'about'
ACCESS_M = 'access_m'
BLOCKS = 'blocks'
CAPSAMEDIR = 'capsamedir'
CAPT_ON = 'capt_on'
CHILD = 'child'
CHILD_CNT_M = 'child_cnt_m'
CONVERT_CNT = 'convert_cnt'
CROSSCAPT = 'crosscapt'
DIFFICULTY = 'difficulty'
EASY_RAND = 'easy_rand'
EMPTIES_M = 'empties_m'
EVENS = 'evens'
EVENS_M = 'evens_m'
FLAGS = 'flags'
GAME_CLASS = 'game_class'
GAME_CONSTANTS = 'game_constants'
GAME_INFO = 'game_info'
GRANDSLAM = 'grandslam'
HELP_FILE = 'help_file'
HOLES = 'holes'
MIN_MOVE = 'min_move'
MLAPS = 'mlaps'
MM_DEPTH = 'mm_depth'
MOVEUNLOCK = 'moveunlock'
MULTICAPT = 'multicapt'
MUSTPASS = 'mustpass'
MUSTSHARE = 'mustshare'
NAME = 'name'
NBR_HOLES = 'nbr_holes'
NBR_START = 'nbr_start'
OPPSIDECAPT = 'oppsidecapt'
ROUNDS = 'rounds'
ROUND_STARTER = 'round_starter'
REPEAT_TURN = 'repeat_turn'
SCORER = 'scorer'
SEEDS_M = 'seeds_m'
SKIP_START = 'skip_start'
SOW_DIRECT = 'sow_direct'
SOW_OWN_STORE = 'sow_own_store'
SOW_START = 'sow_start'
STORES = 'stores'
STORES_M = 'stores_m'
UDIR_HOLES = 'udir_holes'
UDIRECT = 'udirect'
VISIT_OPP = 'visit_opp'
XCPICKOWN = 'xcpickown'
