# -*- coding: utf-8 -*-
"""All the string keys from the configuration files.

Created on Tue Jul 25 07:43:16 2023
@author: Ann"""


ABOUT = 'about'
ACCESS_M = 'access_m'
AI_PARAMS = 'ai_params'
ALGORITHM = 'algorithm'
ALLOW_RULE = 'allow_rule'
BLOCKS = 'blocks'
CAPSAMEDIR = 'capsamedir'
CAPT_ON = 'capt_on'
CAPTTWOOUT = 'capttwoout'
CHILD_CVT = 'child_cvt'
CHILD_CNT_M = 'child_cnt_m'
CHILD_TYPE = 'child_type'
CROSSCAPT = 'crosscapt'
CAPT_MAX = 'capt_max'
CAPT_MIN = 'capt_min'
DIFFICULTY = 'difficulty'
EASY_RAND = 'easy_rand'
EMPTIES_M = 'empties_m'
EVENS = 'evens'
EVENS_M = 'evens_m'
GAME_CLASS = 'game_class'
GAME_CONSTANTS = 'game_constants'
GAME_INFO = 'game_info'
GOAL = 'goal'
GPARAM_ONE = 'gparam_one'
GRANDSLAM = 'grandslam'
HELP_FILE = 'help_file'
HOLES = 'holes'
MIN_MOVE = 'min_move'
MCTS_BIAS = 'mcts_bias'
MCTS_NODES = 'mcts_nodes'
MCTS_POUTS = 'mcts_pouts'
MLAPS = 'mlaps'
MLENGTH = 'mlength'
MM_DEPTH = 'mm_depth'
MOVE_ONE = 'move_one'
MOVEUNLOCK = 'moveunlock'
MULTICAPT = 'multicapt'
MUSTPASS = 'mustpass'
MUSTSHARE = 'mustshare'
NAME = 'name'
NBR_START = 'nbr_start'
NOSINGLECAPT = 'nosinglecapt'
NO_SIDES = 'no_sides'
OPPSIDECAPT = 'oppsidecapt'
PLAYER = 'player'
ROUNDS = 'rounds'
ROUND_STARTER = 'round_starter'
RND_LEFT_FILL = 'rnd_left_fill'
RND_UMOVE = 'rnd_umove'
REPEAT_TURN = 'repeat_turn'
SCORER = 'scorer'
SEEDS_M = 'seeds_m'
SKIP_START = 'skip_start'
SOW_BLKD_DIV = 'sow_blkd_div'
SOW_CAPT_ALL = 'sow_capt_all'
SOW_DIRECT = 'sow_direct'
SOW_OWN_STORE = 'sow_own_store'
SOW_START = 'sow_start'
START_PATTERN = 'start_pattern'
STORES = 'stores'
STORES_M = 'stores_m'
UDIR_HOLES = 'udir_holes'
UDIRECT = 'udirect'
VISIT_OPP = 'visit_opp'
XCPICKOWN = 'xcpickown'
